#!/bin/bash
#
# CH341 OLED plugin - install
# Copyright (c) 2026 foonerd
#
# Installs two prebuilt binaries, a udev rule and a systemd unit.
#
# There is deliberately no apt here. The payload was linked against only
# libraries present on a stock Volumio image, so the plugin installs with
# no network access and no package version drift:
#
#   mpd_oled        libmpdclient2 (via mpc), libusb-1.0-0 (via usbutils),
#                   libudev, libm, libgcc_s, libpthread, libc
#   mpd_oled_cava   libasound2 (Assets), libfftw3, libm, libc
#
# libiniparser is statically linked into mpd_oled_cava because it is the
# one library cava needs that Volumio does not ship.
#
# Nothing outside the paths listed in uninstall.sh is touched, and no
# system configuration file is modified, so a system update leaves all of
# it alone.

set -e

PLUGIN_DIR=/data/plugins/system_hardware/ch341_oled

echo "Installing CH341 OLED plugin"

########################################################################
# Payload
########################################################################
echo "Installing mpd_oled and cava"

if [ ! -f "$PLUGIN_DIR/bin/mpd_oled" ] || [ ! -f "$PLUGIN_DIR/bin/mpd_oled_cava" ]; then
  echo "ERROR: the binary payload is missing from $PLUGIN_DIR/bin"
  echo "plugininstallend"
  exit 1
fi

sudo install -m 755 "$PLUGIN_DIR/bin/mpd_oled" /usr/local/bin/mpd_oled
sudo install -m 755 "$PLUGIN_DIR/bin/mpd_oled_cava" /usr/local/bin/mpd_oled_cava

########################################################################
# Device permissions
#
# The transport talks to the raw USB device, so the i2c group plays no
# part. volumio is already in audio, so the rule grants that group
# access. Rules apply as devices appear, hence the trigger for an
# adapter that is already plugged in.
########################################################################
echo "Installing udev rule for the CH341A"
sudo tee /etc/udev/rules.d/60-ch341-i2c.rules >/dev/null <<'EOF'
# CH341A in I2C/SPI/GPIO mode - userspace access for the ch341_oled plugin
SUBSYSTEM=="usb", ATTR{idVendor}=="1a86", ATTR{idProduct}=="5512", MODE="0660", GROUP="audio", TAG+="uaccess"
EOF
sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=usb --attr-match=idVendor=1a86 || true

########################################################################
# Remove any out-of-tree CH341 kernel module
#
# Two drivers contending for one adapter has been observed to deadlock
# the kernel side hard enough to require a power cycle. If the user
# previously followed the kernel module instructions, take it out of the
# way.
########################################################################
if lsmod | grep -q i2c_ch341_usb; then
  echo "Removing the loaded i2c-ch341-usb kernel module"
  sudo rmmod i2c-ch341-usb || true
fi
if [ -e "/lib/modules/$(uname -r)/kernel/drivers/i2c/busses/i2c-ch341-usb.ko" ]; then
  echo "Removing the installed i2c-ch341-usb kernel module"
  sudo rm -f "/lib/modules/$(uname -r)/kernel/drivers/i2c/busses/i2c-ch341-usb.ko"
  sudo depmod -a
fi

########################################################################
# Service
#
# ExecStart runs a script generated by the plugin from its settings, so
# changing a setting needs no root-owned file rewritten.
########################################################################
echo "Installing the ch341_oled service"

# Placeholder, so the unit has something valid to run before the plugin
# first generates the real script on start.
if [ ! -e "$PLUGIN_DIR/start.sh" ]; then
  printf '#!/bin/bash\nexit 0\n' > "$PLUGIN_DIR/start.sh"
  chmod 755 "$PLUGIN_DIR/start.sh"
fi

sudo tee /etc/systemd/system/ch341_oled.service >/dev/null <<EOF
[Unit]
Description=CH341 OLED display
After=network.target sound.target mpd.service
Wants=mpd.service

[Service]
Type=simple
User=volumio
Group=audio
ExecStart=$PLUGIN_DIR/start.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl disable ch341_oled.service || true

echo "plugininstallend"
