#!/bin/bash
#
# CH341 OLED plugin - uninstall
# Copyright (c) 2026 foonerd
#
# Removes exactly what install.sh added, and nothing else. No packages
# were installed and no system configuration file was modified, so there
# is nothing further to undo.

echo "Uninstalling CH341 OLED plugin"

# Service
sudo systemctl stop ch341_oled.service 2>/dev/null || true
sudo systemctl disable ch341_oled.service 2>/dev/null || true
sudo rm -f /etc/systemd/system/ch341_oled.service
sudo systemctl daemon-reload

# Device permissions
sudo rm -f /etc/udev/rules.d/60-ch341-i2c.rules
sudo udevadm control --reload-rules 2>/dev/null || true

# Payload
#
# mpd_oled_cava is removed too. The armhf mpd_oled plugin symlinks that
# name to the distribution's cava rather than installing a file, so if
# both plugins are present this removes a real file the other plugin did
# not create. Reinstalling the other plugin restores its symlink.
sudo rm -f /usr/local/bin/mpd_oled
sudo rm -f /usr/local/bin/mpd_oled_cava

# Generated by the plugin at runtime
rm -f /data/plugins/system_hardware/ch341_oled/start.sh

# The FIFO is created by ALSA on demand and lives in tmpfs, so it
# disappears on reboot regardless. Remove it now so a stale one does not
# confuse anything before then.
rm -f /tmp/ch341_oled_fifo

echo "pluginuninstallend"
